language: go
go:
  - 1.9.4
sudo: false
git:
  depth: 10
branches:
  only:
    - master
install:
  - go get -u -v github.com/gohugoio/hugo
script:
  - hugo --verbose
  - ls -la themes/hucore
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
