baseURL = "https://pavel-drobushevich.github.io/blog"
languageCode = "en-us"
title = "Pavel Drabushevich Tech Blog"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/pdrobushevich\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Pavel Drabushevich Tech Blog"
keywords = ["blog", "programming"]
author = "Pavel Drabushevich"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/pavel-drobushevich"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/pdrobushevich"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.linkedin.com/in/paveldrobushevich/"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
